### ISSUE TITLE
Feature request to export ruadi environment variables to zsh or bash

### ISSUE THREAD

**Issue by Monty** [Jarsop/rualdi#3]
I want to use ruadi aliases for other things like grep, find, etc. that I used to define environment variables for. 
e.g. `grep PUBLISHED_EPISODES $WS/*sh`

So I added this 'radx' alias to my .zshrc_aliases, but it would be nice if I didn't have to:

    alias radx='_radx'
    _radx() {  
    rualdi add $@
    export $1=$(rualdi resolve $1)
    }

I can't quite figure out how to do this in Rust.  :-(

**Comment by Jarsop** [comment]
Hello @Monty , thanks for your proposal. It's a nice trick, I can add this command in the default zsh/bash completion generation. What do you think about adding a feature which generate the environment variable declared by `radx` at each new shell (maybe with a flag in `radx` command to specify than you want keep it otherwise it will be deleted from `rualdi` database) ?

**Comment by Monty** [comment]
I’d find preserving environment variables in new shells useful. I open a lot of new windows. 

I run my zsh hack (radx) in any new shell, it exports the environment variable even though it generates the error about the "alias 'foo' already exists.

Thanks,
Monty

**Comment by Jarsop** [comment]
Hello @Monty, I added a kind of feature as your `radx` but with some additional commands.
Please do not hesitate to come back to give your feedback :smiley:

**Comment by Jarsop** [comment]
Hi @Monty, could you test the feature ?
